.rubocop.yml
manifests/jail.pp

Corrected typo in variable name: maxretry

---

README.md
metadata.json

Transfer module to Vox Pupuli

---

.github/CONTRIBUTING.md
.msync.yml
.sync.yml
.travis.yml
Gemfile
spec/spec_helper.rb

modulesync 1.9.2

---

README.md
manifests/init.pp
spec/acceptance/class_spec.rb
spec/classes/init_spec.rb
templates/Carbon/etc/fail2ban/jail.conf.erb
templates/Core/etc/fail2ban/jail.conf.erb
templates/Final/etc/fail2ban/jail.conf.erb
templates/Maipo/etc/fail2ban/jail.conf.erb
templates/Santiago/etc/fail2ban/jail.conf.erb
templates/Tikanga/etc/fail2ban/jail.conf.erb
templates/jessie/etc/fail2ban/jail.conf.erb
templates/precise/etc/fail2ban/jail.conf.erb
templates/stretch/etc/fail2ban/jail.conf.erb
templates/trusty/etc/fail2ban/jail.conf.erb
templates/wheezy/etc/fail2ban/jail.conf.erb
templates/xenial/etc/fail2ban/jail.conf.erb

This PR allows banaction to be managed by Puppet, in the case where you want to have a custom banaction defined.
Fixes #64

Allow banaction to be Puppet managed

---

manifests/jail.pp

Fix typo in parameter default

---

CHANGELOG.md

release 2.3.0

---

metadata.json

allow puppet/extlib 3.x

---

CHANGELOG.md
metadata.json

releae 2.4.1

---

manifests/jail.pp
spec/defines/fail2ban_jail_spec.rb
templates/common/custom_filter.conf.epp

* Add `filter_maxlines` and `filter_datepattern` options to `fail2ban::jail`
* Add tests for new config options

Add filter options

---

.github/CONTRIBUTING.md
.msync.yml
Gemfile
manifests/config.pp
manifests/define.pp
manifests/init.pp
manifests/install.pp
manifests/jail.pp
manifests/service.pp
spec/spec_helper.rb

modulesync 2.8.0

---

.sync.yml
.travis.yml
README.md
metadata.json
spec/acceptance/class_spec.rb
templates/buster/etc/fail2ban/jail.conf.epp

Superseeds https://github.com/voxpupuli/puppet-fail2ban/pull/112

Add Debian10 support

---

.fixtures.yml
metadata.json

update repo links to https

---

metadata.json

allow extlib 5.x

---

README.md
manifests/config.pp
manifests/init.pp
spec/classes/init_spec.rb

Add parameters manage_defaults, manage_firewalld

---

.sync.yml
.travis.yml
README.md
metadata.json
templates/Ubuntu/20.04/etc/fail2ban/jail.conf.epp

This PR adds support for Ubuntu 20.04 LTS.
n/a

Add Ubuntu 20.04 support

---

metadata.json
templates/Debian/11/etc/fail2ban/jail.conf.epp

Add support for Debian 11 bullseye

---

metadata.json

puppet/extlib: Allow 6.x

---

README.md
data/Suse.yaml
manifests/config.pp
metadata.json
templates/OpenSuSE/15/etc/fail2ban/jail.conf.epp

Adding support for OpenSuSE
Does not work on OpenSuSE

initial support for opensuse

---

.github/CONTRIBUTING.md
.github/workflows/ci.yml
.github/workflows/release.yml
.msync.yml
.puppet-lint.rc
Dockerfile
Gemfile
Rakefile
spec/acceptance/class_spec.rb
spec/classes/init_spec.rb
spec/defines/define_spec.rb
spec/defines/fail2ban_jail_spec.rb
spec/spec_helper.rb
spec/spec_helper_acceptance.rb

modulesync 5.2.0

---

.msync.yml
.puppet-lint.rc
Gemfile
Rakefile
spec/spec_helper.rb

modulesync 5.1.0

---

CHANGELOG.md
REFERENCE.md
metadata.json

bump version 4.2.0
add support for ubuntu 22.04

prepare for 4.2.0 release

---

metadata.json

bump puppet extlib version < 8.0.0

---

CHANGELOG.md
metadata.json

release 5.0.2

---

examples/fail2ban-Debian.yaml
examples/fail2ban-RedHat.yaml

Update fail2ban-Debian.yaml
Update fail2ban-RedHat.yaml
replace legacy facts in yaml examples
n/a

replace legacy facts in yaml examples
