voxpupuli/puppet-fail2ban

manifests/jail.pp
templates/common/custom_jail.conf.erb

On RedHat systems there is a nagging systemd backend issue that is causing many headaches. The only brute force way at the moment to avoid getting an automatic systemd backend is to set the default_backend, and backend in each jail, to a value other than systemd or auto.
This pull request adds a parameter, to jail.pp to support an optional backend parameter.

support a backend parameter for jails

---

README.md
examples/fail2ban-Debian.yaml
examples/fail2ban-RedHat.yaml
manifests/init.pp
templates/Carbon/etc/fail2ban/jail.conf.erb
templates/Core/etc/fail2ban/jail.conf.erb
templates/Final/etc/fail2ban/jail.conf.erb
templates/Maipo/etc/fail2ban/jail.conf.erb
templates/Santiago/etc/fail2ban/jail.conf.erb
templates/Tikanga/etc/fail2ban/jail.conf.erb
templates/jessie/etc/fail2ban/jail.conf.erb
templates/xenial/etc/fail2ban/jail.conf.erb

The `sender` email was not variablized as for the `destemail`.
Fixes #51

sender email variabilized

---

README.md

This is not a parameter to the main class and can thus be removed.
Fixes https://github.com/voxpupuli/puppet-fail2ban/issues/40

Remove config_file_ensure

---

manifests/config.pp

Scientific Linux CERN version has an
operatingsystem SLC on clone version 6.

 Use os structured fact instead of flat lsb facts

---

README.md
manifests/init.pp
spec/acceptance/class_spec.rb
spec/classes/init_spec.rb
spec/defines/define_spec.rb
templates/Carbon/etc/fail2ban/jail.conf.erb
templates/Core/etc/fail2ban/jail.conf.erb
templates/Final/etc/fail2ban/jail.conf.erb
templates/Maipo/etc/fail2ban/jail.conf.erb
templates/Santiago/etc/fail2ban/jail.conf.erb
templates/Tikanga/etc/fail2ban/jail.conf.erb
templates/jessie/etc/fail2ban/jail.conf.erb
templates/precise/etc/fail2ban/jail.conf.erb
templates/stretch/etc/fail2ban/jail.conf.erb
templates/trusty/etc/fail2ban/jail.conf.erb
templates/wheezy/etc/fail2ban/jail.conf.erb
templates/xenial/etc/fail2ban/jail.conf.erb

`iptables` is already pretty fiddly on its own. Allowing a user to select a custom chain for Fail2Ban to manage (instead of INPUT) will make this management quite a bit less headache-inducing.
This change doesn't manage the chain, just instructs Fail2Ban to use it, via the config file.

Add configuration option for iptables_chain

---

.sync.yml
.travis.yml
manifests/config.pp
spec/acceptance/class_spec.rb
spec/spec_helper_acceptance.rb

Enable acceptance tests for CentOS 6 and Ubuntu 18.04

Enable acceptance tests for CentOS 6

---

README.md
manifests/jail.pp
metadata.json
templates/common/custom_jail.conf.erb

This pull request adds support for defining ignoreip's in the fail2ban jails.

Add ignoreip parameter to jail class and template

---

manifests/config.pp
templates/stretch/etc/fail2ban/jail.conf.erb

'action' is not working on debian strech.
This change fixes it.
This change also remove the default configuration of all Debian setup,
not only Ubuntu 16.04.

Fix action for strech template

---

metadata.json
templates/stretch/etc/fail2ban/jail.conf.erb

While trying to fix a problem with the Debian Stretch template ([imap3 port is not defined in Debian Stretch](https://github.com/fail2ban/fail2ban/issues/1942)), I realized that the default template of `jail.conf` on Debian Stretch is a slightly modified version of the default template for Debian Jessie, and not the actual default files provided in Debian Stretch.
As stated in this configuration file, `jail.conf` has been *heavily refactored in 0.9.0 release*.
This pull-request integrates the actual default template, adjusted to allow customization through the module.
In order to ease-up reviewing, [here is a diff between the original file as provided in the Debian package and the template included in this PR](https://gist.github.com/smortex/9f2ac096a8c904c4c257ceb549a714bd).
The enabled …

Use the actual default Debian Stretch configuration for jail.conf

---

spec/acceptance/class_spec.rb

~~The Debian Stretch template use a hardcoded sender address: `fail2ban@localhost`.~~
~~This PR use the sender address configured with `$fail2ban::sender` instead.~~
The Debian Stetch template used to have a static sender address, ignoring `$fail2ban::sender`.  This problem was addressed as a side effect of #77 but a unit-test for the correct behavior still makes sense.
n/a

Add unit test for checking sender address

---

manifests/jail.pp
spec/classes/init_spec.rb
spec/defines/fail2ban_jail_spec.rb

epp templates for custom jails and filters are broken due to epp not being able to directly reach into the calling class's variable scope. Workaround implemented by passing the required variables into the epp function call in the defined type code.
Fixes #74 
Fixes #27

Bugfix for broken epp templates

---

manifests/config.pp
manifests/init.pp

Use custom_jails parameter

---

.sync.yml
.travis.yml
README.md
metadata.json
templates/bionic/etc/fail2ban/jail.conf.epp

Support for Ubuntu Bionic (18.04)

Add jail.conf.epp template for bionic

---

manifests/init.pp
metadata.json

Without this, we get:
Warning: This method is deprecated, please use extlib::default_content instead. at ["/etc/puppetlabs/code/modules/fail2ban/manifests/init.pp", 44]:
(location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')

depend on extlib 3 & prefix extlib function call

---

manifests/define.pp

This commit fixes the `default_content`, from extlib module, function usage: this non-namespaced function is deprecated since extlib v3 and have been removed in v5.
Please note that releasing a new version could be welcome by users ;-)
BTW, thanks for your work.

Fix non namespaced extlib function

---

manifests/init.pp
spec/classes/init_spec.rb

Upstream uses a different time format since 2014:
* https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf#L101
Fixes #139

Add support for multiple data types

---

README.md
manifests/config.pp
manifests/init.pp
spec/acceptance/class_spec.rb
spec/classes/init_spec.rb
templates/common/sendmail.conf.epp

Support e-mail notification configuration directly from Puppet/Hiera. 
Fixes #143

Support overriding service notifications (#143)

---

templates/RedHat/6/etc/fail2ban/jail.conf.epp
templates/RedHat/7/etc/fail2ban/jail.conf.epp

These lines were probably commented out by mistake in refactoring (d9d2d03d396fb1d24ff7602d253c9748c99b9cdc).
Btw. there are no acceptance tests for RedHat, it might be safer to use Centos templates (if there are no substantial differences).

Fix apache-badbots on RedHat

---

README.md
metadata.json
templates/AlmaLinux/9/etc/fail2ban/jail.conf.epp
templates/CentOS/9/etc/fail2ban/jail.conf.epp
templates/RedHat/9/etc/fail2ban/jail.conf.epp
templates/Rocky/9/etc/fail2ban/jail.conf.epp

The added jail.conf.epp is identical to the jail.conf.epp for
CentOS 8 as they are the same file in the EPEL packages.
```
/etc/fail2ban/fail2ban.conf | awk '{print $4}'
bac7f6497c1432f50cd04ca64da1a55f211aadc219a4163e91cf69940d970123
```
and
```
/etc/fail2ban/fail2ban.conf | awk '{print $4}'
bac7f6497c1432f50cd04ca64da1a55f211aadc219a4163e91cf69940d970123
```

Support CentOS/RHEL/Alma/Rocky 9

---

metadata.json
spec/classes/init_spec.rb
templates/Ubuntu/22.04/etc/fail2ban/jail.conf.epp

Add support for Ubuntu 22.04, compatible with 22.04 template.
Ubuntu LTS compatibility.

Add support for Ubuntu 22.04

---

templates/Debian/11/etc/fail2ban/jail.conf.epp

This was in fact an exact copy on the Debian 10 config.  Use the Debian
11 configuration as a base and adjust it to match the (not recommanded)
way this module configure fail2ban.

Use actual Debian 11 configuration

---

manifests/jail.pp

When a jail use the systemd backend, it does not _need_ a logpath to be set.

`logpath` is not required when `journalmatch` in provided

---

metadata.json

Allow puppetlabs-stdlib 9.x

---

REFERENCE.md
tasks/banip.json
tasks/banip.rb
tasks/unban.json
tasks/unban.rb
tasks/unbanip.json
tasks/unbanip.rb

The fail2ban-client tool allows a large panel of acions.  Start with the
most simple and frequently used ones to ban/unban IP addresses in
fail2ban jails.
Next time I lock me out of a system through SSH, I will be happy to rely
on these tasks with choria to unlock me.

Add tasks to ban/unban IP addresses in jails

---

README.md
REFERENCE.md
manifests/config.pp
manifests/init.pp
manifests/jail.pp
manifests/service.pp

This PR also defines somes classes as private accordingly with README.

Move description of parameters from README to puppet-strings.

---

REFERENCE.md
manifests/jail.pp
spec/defines/fail2ban_jail_spec.rb
spec/type_aliases/logpath_spec.rb
templates/common/custom_jail.conf.epp
types/logpath.pp

Before this PR a jail was able to monitor only one log file.
But with fail2ban, a jail can monitor several files.
This PR permits to monitor several log files with one jail.

jail logpath can handle several files
